name: CI
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tcsh and byacc (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install tcsh
          sudo apt-get install byacc

      - name: Install dependencies (Darwin)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install --cask xquartz

      - name: Create mamba environment (Darwin)
        if: matrix.os == 'macos-latest'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .build/envs/Darwin.yml

      - name: Create mamba environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .build/envs/Linux.yml

      - name: Build NCL
        run: |
          bash .build/mamba_build.sh

      - name: Run tests
        run: |
          ncl -V
          test "`ncl -V`" = "`cat version`"
          git clone https://github.com/NCAR/ncl_ci_test
          cd ncl_ci_test
          bash run_tests.bash
